# 신경과 전문의 수급현황 {#DemandSupplyNeurologist}

<!-- 1 page -->

<!-- - 통계연보(보건복지통계연보, 건강보험통계연보, 손에 잡히는 의료 심사∙평가 길잡이 등의 최신판 활용)를 활용하여 연도별 (해당과) 전문의 공급 현황을 비롯하여 의료이용(수요) 현황 등에 관해 전반적으로 기술함 (단 년도보다는 연도별 수치 변화를 보는 것이 중요함). -->
<!--     - 예) 최근 10년간 해당 전문과목의 전문의 수가 증가(또는 감소)하고 있는 추세이며, 이들의 요양기관 종별 분포 현황은 @@@@이러함. 그에 반해 국민들의 해당 전문과목에 대한 의료이용량은 감소(또는 증가)하고 있음. 이는 전체 의료이용량 중 해당 전문과목에 대해서 특히 그러함. -->

<!--  - 근거로 통계자료 활용을 권고드림. -->

## 인구 10만명당 신경과 전문의 수 

```{r, include=FALSE}
lapply(c("dplyr", "ggplot2", "knitr", "kableExtra", "lubridate", 
         "tidyr", "gridExtra", "ggpubr"), require, character.only = T)
```

```{r echo=F}
global <- data.frame(
  country = c("Korea", "Italy", "Austria", "Japan", 
              "USA", "USA in 2025", "France", "Germany"), 
              ##  3.8, Sweden 4.2, Qatar (1.78), Tunisia 1.58
  NoNeurol = c(3.57, 10.28, 12.74, 4.38, 
               5.21, 6.21, 3.71, 8.09) 
)
# global <- data.frame(
#   country = c("Korea", "Italy", "Austria", "Japan", "Netherlands", 
#               "Switzerland", "USA", "USA in 2025", "France", "Germany"), 
#               ##  3.8, Sweden 4.2, Qatar (1.78), Tunisia 1.58
#   NoNeurol = c(3.57, 10.28, 12.74, 4.38, 7.33, 
#                6.77, 5.21, 6.21, 3.71, 8.09) 
# )
# USA, (11094 + 3727 - 665*3)/3257 ?
# 2012 16366/3140 = 5.21 2013 16366/3162 = 5.18, 
# 2025 18060/3451 = 5.23, 2025_shouldbe 21440/3451
# Resident 665/year, junior 3727
```

```{r echo=F, fig.width=8, fig.height=4}
global %>% 
  ggplot(aes(country, NoNeurol, color = country)) +
    geom_point(aes(size = NoNeurol)) +
    geom_hline(yintercept = c(0, 3, 6), color = "#999999", size = 0.2) +
    geom_hline(yintercept = c(3.57), color = "red", size = 0.2) +
    theme_bw() +
    theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(size = 0.5, color = "black")) +     
    scale_x_discrete("", limits = global$country[order(global$NoNeurol)]) + 
    scale_y_continuous("Number of Neurologist per 100,000",
                       limits = c(0, 15), breaks = c(0, 3, 6, 9, 12)) +
    scale_size_continuous(guide = F) +
    scale_color_discrete(guide = F) +
    geom_text(aes(label = paste(NoNeurol), vjust = -(NoNeurol*0.07 + 0.5)))
# ggsave("figures/global.png", width = 6.25 * 1.5, height = 3.86)
```

•	인구 10만명당 신경과 전문의의 숫자는 한국이 3.57명 (2018년기준)으로 네덜란드, 일본, 헝가리, 스위스, 칠레 등에 비해 적음.

•	통계청 자료에 의한 2018년 인구는 51,014,947명으로, 인구 10만명당 신경과 전문의 수가 네덜란드 수준인 6명이 되려면 3060명이 필요함 (2018년 전문의 수가1845명이므로 부족분은 1215명).

•	미국의 경우 2012년 기준 인구 10만명당 신경과 전문의는 5.21명이며 2025년에는 6.21명이 필요할 것으로 예상되고 있음.


## 한국의 신경과 전문의 연령별 분포 (2018.4기준)

```{r echo=F}
KNA_db <- readRDS("data/KNA_db.rds")
Korea_pop <- readRDS("data/Korea_pop.rds")
Population_2015 = 510.1 # 51,010,000
```

```{r echo=F, fig.width=8, fig.height=4}
graph_db <- KNA_db %>%
  filter(Position == "Board") %>%
  mutate(Age_group = ((Age_2018 / 5) %>% floor()*5),
         Age_group_end = Age_group + 4) %>%
  filter(Age_2018 < 70)
p0 <- graph_db %>%
  ggplot(aes(factor(Age_group), fill = factor(Age_group))) + 
    geom_bar() +
    theme_bw() +
    theme(panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(size = 0.5, color = "black")) +     
    scale_x_discrete("Age",
                       breaks = graph_db$Age_group,
                       labels = paste(graph_db$Age_group, "-", graph_db$Age_group_end)) +
    scale_y_continuous("Number") +
    scale_fill_discrete(guide = F) +
    geom_text(stat = "count", aes(label = ..count.., y=(..count..)), vjust = -0.5)


graph_db <- KNA_db %>%
  filter(Position == "Board") %>%
  mutate(Age_group = ((Age_2018 / 5) %>% floor()*5),
         Age_group_end = Age_group + 4)
Num_text <- graph_db %>% 
  select(Age_group) %>%
  table %>% as.vector

graph_db %>%
  ggplot(aes(factor(Age_group), fill = factor(Age_group))) + 
    geom_bar() +
    theme_bw() +
    theme(panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(size = 0.5, color = "black")) +     
    scale_x_discrete("Age",
                       breaks = graph_db$Age_group,
                       labels = paste(graph_db$Age_group, "-", graph_db$Age_group_end)) +
    scale_y_continuous("Number") +
    scale_fill_discrete(guide = F) +
    geom_text(stat = "count", aes(label = ..count.., y=(..count..)), vjust = -0.5)

# ggsave("figures/Neurologist_5yr.png")

```



