# 국내외 선행연구 고찰

## 2017.9 전공의 정원정책 수립을 위한 전문의 인력 수요 추계 연구 보고서

### 서론 

<!-- - 의료인력의 쏠림: 지역별, 전문과목별 -->
<!-- - 수급의 불균형: 의료인력의 고령화, 인구의 변화, 수요의 증가, 지역적 편재, (전문과목별 편재)  -->
<!-- - 추계접근방법: 전통적 접근법과 통합적 접근법 -->

- 본 연구는 전문과목별 의료 이용량및 질병양상 예측을 통해 의료이용추계를 진행함.

- 공급은 유입유출법, 수요는 전문의 1일 생산성과 환자 의료 이용율을 이용한 의료수요 계측법을 이용하였음. 

    
    - 반론: 전문의의 연령 분포가 일정한 경우에는 전문의 1일 생산성이 지속적으로 일정하게 유지되겠으나 신경과와 같이 연령별 분포가 차이가 많은 경우에는 전문의 1일 생산성이 일정하게 유지되지 않음. 
    
    - 특히 전문의의 노화에 대한 고려가 있어야 함.

- 주장: 전공의를 근로자로 인식하는 잘못된 인식이 있음. 수련병원의 인력수요에 대응하는 정원정책이 아닌 고령화, 만성질환증가 등에 대응하는 추계가 필요함 

    - 반론: 그러나, 현실적으로는 전공의가 의료의 상당부분을 담당하고 있음. 그리과, 이 공백을 메울 전문의는 아직 부족한 실정임. 예를 들면 입원전담의와 같은 직군에 아직 지원이 별로 없음. 따라서, 전공의가 없을 경우, 대부분의 수련병원에서 의료공백이 발생할것이 명백하며, 현실을 고려하지 않은 발상임.
    
    - 또한, 이런 방식이라면, 공급추계를 할 때 전공의를 의료인력에서 제외해야 하지만, 그렇게 하지 않음. (예를 들면 A병원에 전공의 4명과 전문의 4명이 있다고 할 때, 전공의 숫자는 고려하지 않고, 전문의 숫자가 6명이 되면 의료의 공급량이 1.5배가 된다고 추산함. 전공의가 없으면 전문의의 생산성이 떨어지지 때문에, 전공의가 제공하는 의료를 추계에서 무시한다면 현재 전문의의 진료능력을 과대평가하는 오류를 범하게 됨)
    
    - 수요추계모형에서는 인구학적인 요인과 더불어 보험적용기준의 변화에 따른 변화 (MRI의 보험급여적용등)가 같이 고려되어야 함. 예를 들면 수요가 일정부분 증가할 가능성을 고려한 모델이 같이 제시되어야 함.
    

<!-- - 전문의가 해당 전문과목의 전문의로 기능하고 있는 경우: 18 % -->

<!-- - 전문과목별 쏠림현상의 개선을 위해 진행. -->

<!--     - 정원이 줄어들면서 오히려 지원이 감소하는 경우도 있음. -->

<!--     - 한국은 의료이용시의 장애가 낮은 편인데 OECD와 비교하는 것이 맞을지? -->
<!--     - 공급모형에서는 전공의 충원률 또는 지원률이 같이 고려되어야 함. -->
<!--     - 실제 일하는 인력에 대한 조사가 정기적으로 필요함. -->

<!-- - 앞으로 의료인력 추계 모형연구는 reproducibility가 담보될 수 있도록 raw data를 공개해야 한다. -->
    
### 전문의 수요 추계

- 국내 한국보건사회연구원 오영호(2011, 2014)의 연구와, 정형선(2011)의 연구 및 미국 Bureau of Health Workforce 모형을 참조하여 개발

#### 전제조건

- 현재의 급여 및 연령 구조 동일하다는 가정.

    - 연령구조가 동일하다는 것은 신생과의 경우에는 맞지 않음.
    
- 전체 이용량에서 외래에 대비한 입원의 비중이 변화하지 않고 현재 상태 유지함.

    - 우리나라의 인구분포가 노령인구의 급속한 증가가 있는 상황에서 외래및 입원이 현재와 비슷할 것이라는 가정이 맞지 않음. 
    
- 의사 1인당 생산성의 변화는 없음

    - 전공의가 없어지면서 전문의 1인당 생산성은 떨어짐.
    
    
- 건강보험과 의료급여 포함

    - 비급여를 고려하지 않은 문제가 있음. 비급여가 급여가 되는 상황이 발생하면, 의료수요가 급증할 수 있음 (의료비의 감소로 인한 수요 증가). 

#### 공급추정: 전문의사수

<!-- - 전공의를 고려해야 함 -->
<!-- - 현재 시스템에서는 전공의인력이 의료공급의 상당부분을 차지하고 있는데, 전공의를 감소시킨다면 그만큼 전문의가 더 필요함에도 이에 대한 고려가 없음. (전공의가 없으면 전문의의 생산성이 떨어지기 때문) -->

- 의사에 대한 공급량은 실제 활동하고 있는 의사 수에 의해 측정하되, 심사평가원에서 제공된 자료 이용

    - 심평원의 활동의사수 자료에 대한 검증은 필요할 것임. 에를 들어 주 3일 근무하는 의사는 어떻게 계산이 되고 있는지 확인이 필요함.


- 의사의 연간 근무일수: 365 - (법정공휴일 66일 + 주5일 51일 + 학회 10일)로 추정

    - 연차 휴가, 출산휴가, 육아휴가등에 대한 고려는 없음.

    <!-- - 1년중 평일> 249일, 휴일> 116일. https://zetawiki.com/wiki/연간_공휴일_수,_영업일_수,_근무일_수 -->
    <!-- - 연차 휴가: 간단한 근속년수에 따른 연차가산일 수식 = (근속년수- 1년)/2  (나머지 버림) https://help.jobis.co/hc/ko/articles/115003127813--연차-근로기간에-따른-연차휴가 -->
    <!-- - 출산휴가(90일), 육아휴직 https://help.jobis.co/hc/ko/articles/360001561894--노무-출산휴가-육아휴직-알아보기- -->
    
    
#### 수요추정
- 수요 추정을 위한 의료이용량은 2012-2016년 건강보험, 의료급여 및 보훈 병원의 의원급 병원급 진료 과목별 심사실적을 사용
- 2018-2022년의 의료 공급과 수요를 계산하기 위해서, 공급은 최근 5년간의 평균증가율인 3.7% 그리고 수요도 최근 5년간의 평균 증가율인 2.7%를 적용함
- 이 평균 증가율은 정형선(2011)의 자료와 차이를 보이는데(수요 평균 증가율 6~7%). 이는 최근의 경기 불황으로 의료 수요의 증가폭이 줄어든 것이 반영된 것임.
    
    - 2015년 MERS사태가 고려되지 않으면서 수요를 과소 추정함. 
    - 의학의 발전을 고려하여야 함. 예를 들면 2015년 IA thrombectomy에 대한 연구 다수 발표된 이후 혈전제거술의 time window가 늘어남. 이에따라 급성 뇌졸중의 치료가능 시간이 늘어나면서 (3시간 -> 24시간) 응급 진료인력에 대한 수요가 더 증가하게 됨. 

- 환자 1인당 평균진료시간: 7.9분 (신경과), 8.1분 (일반외과)


<!-- ## 5개과 설문분석 결과와 KPS -->

<!-- - 6. Survey를 정리해서 신경과 관련 부분만 여기에 정리. -->

<!-- - 첫번째로는 근무시간의 과별 불균형  -->
<!--         - 주중 근무시간  -->
<!--         - 주당 근무시간 -->
<!--         - 연당 휴무일 수: 기존의 가정에 비해  -->

<!-- NU: 238, KPS 193 -->


<!-- (추계 연구 또는 인력계획 연구 중심) : 가장 중요한 챕터! (5~6page) -->

<!-- 되도록 국내와 국외 연구를 구분하거나, 아래의 1), 2)로 구분하여 일정 기준에 따라 작성하는 것이 좋을 듯 합니다. 이 부분 역시 내부적으로 논의하여 통일성 있게 작성하면 좋겠습니다. 다만, 문헌리뷰 작성틀에 맞게 각 과별로 리뷰한 문헌의 결과를 작성해 주시는 것이 가장 중요합니다. 리뷰 결과가 풍성해야 문제제기를 하거나 소결을 작성하시는 데 더 수월하실 것 같습니다. (적어도 최신 연구 국내, 국외 각 5편 정도) -->

<!-- -	국내와 국외에서 해당 전문과목에 대해 추계한 연구 (추계뿐 아니라 인력계획에 관한 연구도 포괄하는 것이 더 좋을 것임)를 중심으로 고찰 내용을 기술함. -->
<!--   - 예) ‘Somekh 등(2019)은 이스라엘 내 소아과 전문의사 인력 계획에 관하여….(어떤 내용으로) 연구를 수행하였고, 주로 (어떤 이슈)를 중점적으로 살펴보았으며, 연구 결과 (결론)는 어떠했다.’ 와 같은 식으로 서술하되 조금 더 상세하게 연구자별 내용을 언급해 주시는 것이 좋을 것 같습니다. -->

<!-- 1.주요 연구 동향 : 국내외 연구의 핵심 내용을 요약정리하는 의미(단, 해당과목에 특이적인 연구 위주로 고찰한 내용을 담으며, 전체 전문의 수급 연구 전반에 관한 문헌고찰은 연구 도입부(이론적 배경 등의 챕터)에 추가하는 것이 좋겠음. -->

<!-- 2. 문헌리뷰 작성틀(엑셀) 내용 기반 방법론 관련 부분 : 추계기간, 변수 또는 시나리오, 추계결과 위주로 서술 (삽입할 표 형식은 추후 다시 공유해드리겠습니다) -->

